local this = {
    {
        id = "longsword",
        name = "Longsword",
        ids = {
            "daedric claymore",
            "dwarven claymore",
            "glass claymore",
            "iron claymore",
            "nordic claymore",
            "steel claymore",
            "adamantium_claymore",
            "BM nordic silver claymore",
            "BM nordic silver claymore_ber",
            "silver claymore",
            "daedric longsword",
            "silver longsword",
            "glass longsword",
            "iron longsword",
            "BM ice longsword",
            "steel longsword",
            "ebony longsword",
            "BM nordic silver longsword",
            "BM nordic silver longsword_ber",
            "BM nordic_longsword_tracker",
            "BM hunstman longsword",
        }
    },
    {
        id = "candle",
        name = "Candle",
        ids = {
            "Light_Com_Candle_01",
            "Light_Com_Candle_12",
            "Light_Com_Candle_12_77",
            "Light_Com_Candle_12_off",
            "Light_Com_Candle_14",
            "Light_Com_Candle_14_77",
            "Light_Com_Candle_15",
            "Light_Com_Candle_16",
            "Light_Com_Candle_16_77",
            "Light_Com_Candle_01_64",
            "light_com_candle_03",
            "light_com_candle_03_64",
            "light_com_candle_05",
            "light_com_candle_05_off",
            "light_com_candle_05_64",
            "light_com_candle_08",
            "light_com_candle_08_64",
            "light_com_candle_09",
            "light_com_candle_09_64",
            "light_com_candle_09_off",
            "light_com_candle_09_128",
            "light_com_candle_10",
            "light_com_candle_10_64",
            "light_com_candle_10_128",
            "light_com_candle_10_off",
            "light_de_candle_ivory_64",
            "light_de_candle_ivory_01",
            "light_de_candle_ivory_01_64",
            "light_de_candle_ivory_01_128",
            "light_de_candle_ivory_01_off",
            "light_de_candle_ivory_dead",
            "light_de_candle_red_01_64",
            "light_de_candle_red_01",
            "light_de_candle_red_02",
            "light_de_candle_red_02_64",
            "light_de_candle_green_01",
            "light_de_candle_green_01_64",
            "light_de_candle_green_01_Off",
            "light_de_candle_blue_01",
            "light_de_candle_blue_01_64",
            "light_de_candle_blue_01_Off",
            "light_de_candle_blue_02",
            "light_de_candle_blue_02_64",
            "light_de_candle_blue_02_100",
            "light_de_candle_15_64",
            "light_de_candle_16_64",
            "light_de_candle_17_64",
            "light_com_candle_02",
            "light_com_candle_01_off",
            "light_de_candle_03",
            "light_de_candle_03_64",
            "light_de_candle_05",
            "light_de_candle_05_64",
            "light_de_candle_05_77",
            "light_de_candle_06",
            "light_de_candle_06_64",
            "light_de_candle_06_off",
            "light_de_candle_128_off",
            "light_de_candle_10",
            "light_de_candle_10_64",
            "light_de_candle_11",
            "light_de_candle_11_off",
            "light_de_candle_11_64",
            "light_de_candle_12",
            "light_de_candle_12_64",
            "light_de_candle_13",
            "light_de_candle_13_64",
            "light_de_candle_13_off",
            "light_de_candle_14",
            "light_de_candle_14_64",
            "light_de_candle_15",
            "light_de_candle_15_off",
            "light_de_candle_16",
            "light_de_candle_17",
            "light_de_candle_18",
            "light_de_candle_18_64",
            "light_de_candle_19",
            "light_de_candle_19_64",
            "light_de_candle_19_256",
            "Light_De_Candle_20",
            "Light_De_Candle_21",
            "Light_De_Candle_22",
            "Light_De_Candle_24",
            "Light_De_Candle_24_64",
            "Light_De_Candle_25",
            "Light_De_Candle_26",
            "light_com_candle_02_64",
            "Light_De_Candle_23_177",
            "Light_De_Candle_23",
            "light_com_Dae_cursed_candle_10",
        }
    },
    {
        id = "skull",
        name = "Skull",
        ids = {
            "misc_skull00",
            "misc_skull10",
            "misc_Skull_Llevule",
            "misc_skull_griss",
            "misc_skull_griss_floor",
            "misc_skull_Skaal",
            "misc_skull_oddfrid",
            "misc_argonianhead_01",
        }
    },
    {
        id = "instrument",
        name = "Instrument",
        ids = {
            "misc_de_drum_01",
            "misc_de_drum_02",
            "misc_de_lute_01",
            "misc_de_lute_01_phat",
        }
    },
    {
        id = "ash_statue",
        name = "Ash Statue",
        ids = {
            "misc_6th_ash_statue_01",
            "misc_6th_ash_hrcs",
            "misc_6th_ash_hrmm",
        }
    },
    {
        id = "6th_house",
        name = "6th House",
        ids = {
            "misc_goblet_dagoth",
            "misc_de_goblet_04_dagoth",
            "ingred_corprus_weepings_01",
            "ingred_6th_corprusmeat_01",
            "ingred_6th_corprusmeat_02",
            "ingred_6th_corprusmeat_03",
            "ingred_6th_corprusmeat_04",
            "ingred_6th_corprusmeat_05",
            "ingred_6th_corprusmeat_06",
            "ingred_6th_corprusmeat_07",
            "6th bell hammer",
        }
    },
    {
        id = "skooma_pipe",
        name = "Skooma Pipe",
        ids = {
            "apparatus_a_spipe_01",
            "apparatus_a_spipe_tsiya"
        }
    },
    {
        id = "skooma",
        name = "Skooma",
        ids = {
            "potion_skooma_01"
        }
    },
    {
        id = "ashlander_lit",
        name = "Ashlander Text",
        ids = {
            "bk_Ashland_Hymns",
            "bk_five_far_stars",
            "bk_thelostprophecy",
            "bk_words_of_the_wind",
        }
    },
    {
        id = "ashlander_cuirass",
        name = "Ashlander Cuirass",
        ids = {
            "bonemold_armun-an_cuirass",
            "netch_leather_boiled_cuirass",
            "erur_dan_cuirass_unique",
            "bonemold_gah-julan_cuirass",
            "indoril cuirass",
            "bonemold_cuirass",
            "chitin cuirass",
        }
    }
}

return this